const navSlide = () => {
    const burger = document.querySelector('.burger');
    const nav = document.querySelector('.nav-links');
    const navLinks = document.querySelectorAll('.nav-links li');

    burger.addEventListener('click', () => {
        // Toggle Nav
        nav.classList.toggle('nav-active');

        // Animation des liens
        navLinks.forEach((link, index) => {
            if (link.style.animation) {
                link.style.animation = '';
            } else {
                link.style.animation = `navLinkFade 0.5s ease forwards ${index / 7 + 0.3}s`;
            }
        });

        // Animation du burger
        burger.classList.toggle('toggle');
    });
}

// Appel de la fonction
navSlide();

// Smooth scrolling pour les ancres (optionnel car géré par CSS html {scroll-behavior: smooth} moderne, 
// mais utile pour compatibilité)
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
        e.preventDefault();

        document.querySelector(this.getAttribute('href')).scrollIntoView({
            behavior: 'smooth'
        });
    });
});

// ==== BOUTON RETOUR EN HAUT ====
const scrollToTopBtn = document.getElementById('scrollToTop');

window.addEventListener('scroll', () => {
    // Afficher le bouton après 300px de scroll
    if (window.pageYOffset > 300) {
        scrollToTopBtn.classList.add('visible');
    } else {
        scrollToTopBtn.classList.remove('visible');
    }
    
    // Barre de progression
    updateScrollProgress();
});

scrollToTopBtn.addEventListener('click', () => {
    window.scrollTo({
        top: 0,
        behavior: 'smooth'
    });
});

// ==== BARRE DE PROGRESSION ====
const scrollProgress = document.querySelector('.scroll-progress');

function updateScrollProgress() {
    const windowHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
    const scrolled = (window.pageYOffset / windowHeight) * 100;
    scrollProgress.style.width = scrolled + '%';
}

// ==== ANIMATION AU SCROLL (FADE IN) ====
const observerOptions = {
    threshold: 0.1,
    rootMargin: '0px 0px -50px 0px'
};

const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
        if (entry.isIntersecting) {
            entry.target.style.opacity = '1';
            entry.target.style.transform = 'translateY(0)';
        }
    });
}, observerOptions);

// Appliquer l'animation aux cartes de projet et compétences
document.querySelectorAll('.project-card, .skill-card, .stat-item').forEach(el => {
    el.style.opacity = '0';
    el.style.transform = 'translateY(30px)';
    el.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
    observer.observe(el);
});

// ==== EFFET DE FRAPPE (TYPEWRITER) ====
const subtitleElement = document.querySelector('.hero h2');
if (subtitleElement) {
    const text = subtitleElement.textContent;
    subtitleElement.textContent = '';
    let i = 0;
    
    function typeWriter() {
        if (i < text.length) {
            subtitleElement.textContent += text.charAt(i);
            i++;
            setTimeout(typeWriter, 100);
        }
    }
    
    // Démarrer l'effet après un court délai
    setTimeout(typeWriter, 500);
}

// ==== SYSTÈME DE TRADUCTION ====
const translations = {
    fr: {
        nav_home: "Accueil",
        nav_about: "À propos",
        nav_skills: "Compétences",
        nav_projects: "Projets",
        nav_contact: "Contact",
        hero_greeting: "Salut, je suis",
        hero_title: "Étudiant en Développement Web",
        hero_description: "J'ai 18 ans et je transforme des idées en sites web fonctionnels et créatifs.",
        hero_btn_projects: "Voir mes projets",
        hero_btn_contact: "Me contacter",
        about_title: "À propos de moi",
        about_p1: "Passionné par le numérique depuis mon plus jeune âge, j'ai décidé de transformer cette passion en métier. Actuellement en formation de développement web, j'apprends chaque jour de nouvelles technologies et je développe mes compétences à travers des projets concrets.",
        about_p2: "Mon approche du développement se base sur trois piliers : la qualité du code, l'expérience utilisateur et l'apprentissage continu. Je suis curieux, persévérant et j'aime résoudre des problèmes complexes grâce au code.",
        about_p3: "Toujours à l'écoute des dernières tendances du web, je m'efforce de créer des sites modernes, performants et accessibles.",
        stat_years: "Ans",
        stat_projects: "Projets",
        stat_technologies: "Technologies",
        stat_motivation: "Motivation",
        skills_title: "Mes Compétences",
        projects_title: "Mes Projets",
        project1_title: "Projet docker Laravel",
        project1_description: "Deux sites Laravel partagent une MySQL via Docker (Nginx, PHP‑FPM) : conteneurisation et scalabilité.",
        project2_title: "Site To-Do List",
        project2_description: "Todo: créer, filtrer, rechercher ; données en LocalStorage ; UI moderne et responsive.",
        project3_title: "Portfolio V1",
        project3_description: "Portfolio responsive, navigation fluide, animations CSS.",
        project_link: "Voir le code",
        contact_title: "Contactez-moi",
        contact_subtitle: "Une opportunité ou une question ? N'hésitez pas !",
        contact_name: "Votre Nom",
        contact_email: "Votre Email",
        contact_message: "Votre Message",
        contact_btn: "Envoyer",
        footer_rights: "Tous droits réservés.",
        back_to_projects: "Retour aux projets",
        // Docker page
        docker_title: "Projet Docker Laravel",
        docker_subtitle: "Architecture multi-applications avec base de données partagée via conteneurisation Docker",
        docker_about_title: "À propos du projet",
        docker_about_p1: "Ce projet représente une solution d'architecture moderne permettant de connecter deux applications web distinctes à une base de données MySQL unique via Docker. L'objectif principal était de créer un environnement de développement reproductible et isolé tout en permettant le partage de données entre plusieurs applications Laravel.",
        docker_about_p2: "La conteneurisation Docker garantit que chaque service fonctionne dans son propre environnement isolé, ce qui simplifie le déploiement et réduit les conflits de dépendances. Cette approche démontre une compréhension approfondie des concepts DevOps et des architectures cloud-native.",
        docker_objectives_title: "Objectifs",
        docker_obj_1: "Créer une architecture multi-applications avec partage de données centralisé",
        docker_obj_2: "Implémenter une solution conteneurisée complète avec Docker",
        docker_obj_3: "Assurer l'isolation des environnements tout en permettant la communication",
        docker_obj_4: "Optimiser la persistance des données avec des volumes Docker",
        docker_obj_5: "Faciliter le déploiement et la maintenance des applications",
        docker_obj_6: "Mettre en place une infrastructure évolutive et maintenable",
        docker_features_title: "Fonctionnalités clés",
        docker_feat1_title: "Conteneurisation complète",
        docker_feat1_desc: "Tous les services sont conteneurisés pour garantir la portabilité et l'isolation.",
        docker_feat2_title: "Base de données partagée",
        docker_feat2_desc: "MySQL centralisé accessible par plusieurs applications Laravel simultanément.",
        docker_feat3_title: "Nginx & PHP-FPM",
        docker_feat3_desc: "Configuration optimisée de Nginx comme reverse proxy avec PHP-FPM.",
        docker_feat4_title: "Volumes persistants",
        docker_feat4_desc: "Gestion des volumes Docker pour la persistance des données et du code.",
        docker_feat5_title: "Réseau Docker",
        docker_feat5_desc: "Configuration réseau permettant la communication inter-conteneurs.",
        docker_feat6_title: "Docker Compose",
        docker_feat6_desc: "Orchestration simplifiée de tous les services avec un fichier YAML.",
        docker_architecture_title: "Architecture technique",
        docker_arch_services: "Services Docker",
        docker_arch_service1: "Premier site web avec son propre conteneur Nginx/PHP-FPM",
        docker_arch_service2: "Deuxième site web avec configuration similaire mais indépendante",
        docker_arch_service3: "Serveur de base de données partagé entre les deux applications",
        docker_arch_service4: "Serveur web et reverse proxy pour chaque application",
        docker_arch_service5: "Gestionnaire de processus FastCGI pour PHP",
        docker_arch_config: "Configuration",
        docker_arch_config_intro: "Le projet utilise Docker Compose pour orchestrer tous les services. Chaque service est défini avec :",
        docker_arch_config1: "Des images Docker officielles ou personnalisées",
        docker_arch_config2: "Des volumes pour la persistance et le développement",
        docker_arch_config3: "Des variables d'environnement pour la configuration",
        docker_arch_config4: "Des ports exposés pour l'accès externe",
        docker_arch_config5: "Des dépendances entre services pour l'ordre de démarrage",
        docker_tech_title: "Technologies utilisées",
        docker_tech1: "Plateforme de conteneurisation pour l'isolation et la portabilité",
        docker_tech2: "Outil d'orchestration pour gérer les multi-conteneurs",
        docker_tech3: "Framework PHP moderne pour les applications web",
        docker_tech4: "Système de gestion de base de données relationnelle",
        docker_tech5: "Serveur web haute performance et reverse proxy",
        docker_tech6: "Gestionnaire de processus PHP FastCGI",
        docker_skills_title: "Compétences développées",
        docker_skill1: "Maîtrise de Docker et de la conteneurisation",
        docker_skill2: "Configuration et orchestration de services avec Docker Compose",
        docker_skill3: "Gestion des réseaux Docker et de la communication inter-conteneurs",
        docker_skill4: "Administration de bases de données MySQL",
        docker_skill5: "Configuration de serveurs web Nginx",
        docker_skill6: "Compréhension des architectures microservices",
        docker_skill7: "Gestion des volumes et de la persistance des données",
        docker_skill8: "Débogage et résolution de problèmes dans des environnements conteneurisés",
        docker_challenges_title: "Défis relevés",
        docker_challenge1: "Configuration du partage de base de données entre plusieurs applications",
        docker_challenge2: "Gestion des permissions et de la sécurité dans les conteneurs",
        docker_challenge3: "Optimisation de la configuration Nginx pour les performances",
        docker_challenge4: "Mise en place de volumes persistants pour le développement",
        docker_challenge5: "Résolution des problèmes de réseau entre conteneurs",
        docker_challenge6: "Configuration des variables d'environnement Laravel pour Docker",
        view_code_github: "Voir le code sur GitHub",
        contact_me: "Me contacter",
        // TodoList page
        todo_title: "Site To‑Do List",
        todo_eyebrow: "Gestion de tâches — JavaScript pur",
        todo_hero_title: "Organisateur personnel élégant",
        todo_hero_lead: "Un site web moderne qui transforme la gestion quotidienne des tâches en une expérience fluide et intuitive. Conçu pour fonctionner entièrement offline avec persistance locale des données.",
        todo_context_title: "Contexte & Vision",
        todo_context_p1: "Ce projet est né d'un constat simple : les gestionnaires de tâches existants sont souvent surchargés de fonctionnalités inutiles ou nécessitent une connexion permanente. L'objectif était de créer un site minimaliste, rapide, et accessible sans dépendance serveur.",
        todo_context_p2: "En exploitant l'API LocalStorage du navigateur, le site garantit une disponibilité 100% offline tout en offrant une interface moderne avec système de priorités, dates d'échéance et recherche en temps réel.",
        todo_feat1_title: "Création instantanée",
        todo_feat1_desc: "Ajout de tâches avec titre, détails, priorité et date limite en un clic.",
        todo_feat2_title: "Filtres avancés",
        todo_feat2_desc: "Vue par statut, priorité ou date. Recherche dynamique multi‑critères.",
        todo_feat3_title: "Édition en ligne",
        todo_feat3_desc: "Modification directe sans popup, validation automatique.",
        todo_feat4_title: "Design adaptatif",
        todo_feat4_desc: "Interface optimisée mobile/desktop avec thème sombre élégant.",
        todo_feat5_title: "Gestion sélective",
        todo_feat5_desc: "Suppression unique ou en masse avec confirmation visuelle.",
        todo_feat6_title: "100% Offline",
        todo_feat6_desc: "Aucune connexion requise, données stockées localement.",
        todo_implementation_title: "Implémentation technique",
        todo_impl_arch: "Architecture modulaire",
        todo_impl_arch1: "objet central synchronisant UI et storage",
        todo_impl_arch2: "génération DOM optimisée par templates",
        todo_impl_arch3: "gestion performante des interactions",
        todo_impl_arch4: "sauvegarde à chaque modification",
        todo_impl_tech: "Technologies clés",
        todo_impl_tech1_title: "Front‑end",
        todo_impl_tech1_desc: "HTML5 sémantique, CSS3 Grid/Flexbox",
        todo_impl_tech2_title: "Logique",
        todo_impl_tech2_desc: "JavaScript ES6+ (classes, modules)",
        todo_impl_tech3_title: "Stockage",
        todo_impl_tech3_desc: "LocalStorage avec sérialisation JSON",
        todo_impl_tech4_title: "UX",
        todo_impl_tech4_desc: "Transitions CSS, états hover/focus",
        todo_features_title: "Fonctionnalités détaillées",
        todo_feature1_title: "Système de priorités",
        todo_feature1_desc: "Trois niveaux (Aucune, Moyenne, Haute) avec indicateurs visuels et tri automatique.",
        todo_feature2_title: "Dates d'échéance",
        todo_feature2_desc: "Sélecteur natif HTML5, format localisé, et alertes visuelles pour les deadlines.",
        todo_feature3_title: "Recherche intelligente",
        todo_feature3_desc: "Filtrage temps réel sur titre et détails, insensible à la casse.",
        todo_feature4_title: "Compteurs dynamiques",
        todo_feature4_desc: "Statistiques en temps réel : tâches en cours vs terminées.",
        todo_challenges_title: "Défis techniques",
        todo_challenge1: "Synchronisation état/localStorage sans latence perceptible",
        todo_challenge2: "Gestion des edge cases (quota storage, corruption JSON)",
        todo_challenge3: "Performance avec listes de 100+ tâches",
        todo_challenge4: "Édition inline sans conflit focus/blur",
        todo_solutions_title: "Solutions apportées",
        todo_solution1: "Debounce sur sauvegardes + fallback gracieux",
        todo_solution2: "Validation stricte et sanitization des entrées",
        todo_solution3: "Virtual scrolling et lazy rendering",
        todo_solution4: "State machine pour les modes d'interaction",
        todo_learnings_title: "Apprentissages & Évolutions",
        todo_learnings_p1: "Ce projet a été une opportunité d'approfondir la manipulation du DOM sans framework, de maîtriser les API natives du navigateur, et de concevoir une architecture maintenable pour du JavaScript vanilla. Il a également permis de développer une sensibilité UX forte, notamment sur la gestion des états de chargement et les feedbacks visuels.",
        todo_learnings_p2: "Les évolutions futures envisagées incluent : synchronisation cloud optionnelle, PWA avec service worker, tags/catégories pour tâches, et export/import au format JSON.",
        test_site: "Voir le site",
        discuss_project: "Discuter du projet"
    },
    en: {
        nav_home: "Home",
        nav_about: "About",
        nav_skills: "Skills",
        nav_projects: "Projects",
        nav_contact: "Contact",
        hero_greeting: "Hi, I'm",
        hero_title: "Web Development Student",
        hero_description: "I'm 18 years old and I transform ideas into functional and creative websites.",
        hero_btn_projects: "View my projects",
        hero_btn_contact: "Contact me",
        about_title: "About Me",
        about_p1: "Passionate about digital technology since my early age, I decided to turn this passion into a career. Currently studying web development, I learn new technologies every day and develop my skills through concrete projects.",
        about_p2: "My approach to development is based on three pillars: code quality, user experience, and continuous learning. I'm curious, persevering, and I love solving complex problems through code.",
        about_p3: "Always listening to the latest web trends, I strive to create modern, performant, and accessible websites.",
        stat_years: "Years",
        stat_projects: "Projects",
        stat_technologies: "Technologies",
        stat_motivation: "Motivation",
        skills_title: "My Skills",
        projects_title: "My Projects",
        project1_title: "Docker Laravel Project",
        project1_description: "Two Laravel sites share one MySQL via Docker (Nginx, PHP‑FPM); containerized and scalable.",
        project2_title: "To-Do List Website",
        project2_description: "Task manager: create, filter, search; LocalStorage persistence; modern responsive UI.",
        project3_title: "Portfolio V1",
        project3_description: "Responsive portfolio with smooth nav and CSS animations.",
        project_link: "View code",
        contact_title: "Contact Me",
        contact_subtitle: "An opportunity or a question? Don't hesitate!",
        contact_name: "Your Name",
        contact_email: "Your Email",
        contact_message: "Your Message",
        contact_btn: "Send",
        footer_rights: "All rights reserved.",
        back_to_projects: "Back to projects",
        // Docker page
        docker_title: "Docker Laravel Project",
        docker_subtitle: "Multi-application architecture with shared database via Docker containerization",
        docker_about_title: "About the project",
        docker_about_p1: "This project represents a modern architecture solution allowing two distinct web applications to connect to a single MySQL database via Docker. The main objective was to create a reproducible and isolated development environment while allowing data sharing between multiple Laravel applications.",
        docker_about_p2: "Docker containerization ensures that each service operates in its own isolated environment, simplifying deployment and reducing dependency conflicts. This approach demonstrates a deep understanding of DevOps concepts and cloud-native architectures.",
        docker_objectives_title: "Objectives",
        docker_obj_1: "Create multi-application architecture with centralized data sharing",
        docker_obj_2: "Implement a complete containerized solution with Docker",
        docker_obj_3: "Ensure environment isolation while allowing communication",
        docker_obj_4: "Optimize data persistence with Docker volumes",
        docker_obj_5: "Facilitate application deployment and maintenance",
        docker_obj_6: "Set up scalable and maintainable infrastructure",
        docker_features_title: "Key Features",
        docker_feat1_title: "Complete containerization",
        docker_feat1_desc: "All services are containerized to ensure portability and isolation.",
        docker_feat2_title: "Shared database",
        docker_feat2_desc: "Centralized MySQL accessible by multiple Laravel applications simultaneously.",
        docker_feat3_title: "Nginx & PHP-FPM",
        docker_feat3_desc: "Optimized Nginx configuration as reverse proxy with PHP-FPM.",
        docker_feat4_title: "Persistent volumes",
        docker_feat4_desc: "Docker volume management for data and code persistence.",
        docker_feat5_title: "Docker network",
        docker_feat5_desc: "Network configuration enabling inter-container communication.",
        docker_feat6_title: "Docker Compose",
        docker_feat6_desc: "Simplified orchestration of all services with a YAML file.",
        docker_architecture_title: "Technical Architecture",
        docker_arch_services: "Docker Services",
        docker_arch_service1: "First website with its own Nginx/PHP-FPM container",
        docker_arch_service2: "Second website with similar but independent configuration",
        docker_arch_service3: "Shared database server between both applications",
        docker_arch_service4: "Web server and reverse proxy for each application",
        docker_arch_service5: "FastCGI process manager for PHP",
        docker_arch_config: "Configuration",
        docker_arch_config_intro: "The project uses Docker Compose to orchestrate all services. Each service is defined with:",
        docker_arch_config1: "Official or custom Docker images",
        docker_arch_config2: "Volumes for persistence and development",
        docker_arch_config3: "Environment variables for configuration",
        docker_arch_config4: "Exposed ports for external access",
        docker_arch_config5: "Service dependencies for startup order",
        docker_tech_title: "Technologies Used",
        docker_tech1: "Containerization platform for isolation and portability",
        docker_tech2: "Orchestration tool to manage multi-containers",
        docker_tech3: "Modern PHP framework for web applications",
        docker_tech4: "Relational database management system",
        docker_tech5: "High-performance web server and reverse proxy",
        docker_tech6: "PHP FastCGI process manager",
        docker_skills_title: "Skills Developed",
        docker_skill1: "Docker and containerization mastery",
        docker_skill2: "Service configuration and orchestration with Docker Compose",
        docker_skill3: "Docker network management and inter-container communication",
        docker_skill4: "MySQL database administration",
        docker_skill5: "Nginx web server configuration",
        docker_skill6: "Understanding of microservices architectures",
        docker_skill7: "Volume management and data persistence",
        docker_skill8: "Debugging and troubleshooting in containerized environments",
        docker_challenges_title: "Challenges Overcome",
        docker_challenge1: "Database sharing configuration between multiple applications",
        docker_challenge2: "Managing permissions and security in containers",
        docker_challenge3: "Optimizing Nginx configuration for performance",
        docker_challenge4: "Setting up persistent volumes for development",
        docker_challenge5: "Resolving network issues between containers",
        docker_challenge6: "Configuring Laravel environment variables for Docker",
        todo_feat1_title: "Instant creation",
        todo_feat1_desc: "Add tasks with title, details, priority and deadline in one click.",
        todo_feat2_title: "Advanced filters",
        todo_feat2_desc: "View by status, priority or date. Multi-criteria dynamic search.",
        todo_feat3_title: "Inline editing",
        todo_feat3_desc: "Direct modification without popup, automatic validation.",
        todo_feat4_title: "Adaptive design",
        todo_feat4_desc: "Mobile/desktop optimized interface with elegant dark theme.",
        todo_feat5_title: "Selective management",
        todo_feat5_desc: "Single or bulk deletion with visual confirmation.",
        todo_feat6_title: "100% Offline",
        todo_feat6_desc: "No connection required, data stored locally.",
        todo_implementation_title: "Technical Implementation",
        todo_impl_arch: "Modular architecture",
        todo_impl_arch1: "central object synchronizing UI and storage",
        todo_impl_arch2: "template-optimized DOM generation",
        todo_impl_arch3: "performant interaction management",
        todo_impl_arch4: "save on every modification",
        todo_impl_tech: "Key technologies",
        todo_impl_tech1_title: "Front‑end",
        todo_impl_tech1_desc: "Semantic HTML5, CSS3 Grid/Flexbox",
        todo_impl_tech2_title: "Logic",
        todo_impl_tech2_desc: "JavaScript ES6+ (classes, modules)",
        todo_impl_tech3_title: "Storage",
        todo_impl_tech3_desc: "LocalStorage with JSON serialization",
        todo_impl_tech4_title: "UX",
        todo_impl_tech4_desc: "CSS transitions, hover/focus states",
        todo_features_title: "Detailed Features",
        todo_feature1_title: "Priority system",
        todo_feature1_desc: "Three levels (None, Medium, High) with visual indicators and automatic sorting.",
        todo_feature2_title: "Deadlines",
        todo_feature2_desc: "Native HTML5 selector, localized format, and visual alerts for deadlines.",
        todo_feature3_title: "Smart search",
        todo_feature3_desc: "Real-time filtering on title and details, case-insensitive.",
        todo_feature4_title: "Dynamic counters",
        todo_feature4_desc: "Real-time statistics: ongoing vs completed tasks.",
        todo_challenges_title: "Technical Challenges",
        todo_challenge1: "State/localStorage synchronization without perceptible latency",
        todo_challenge2: "Managing edge cases (storage quota, JSON corruption)",
        todo_challenge3: "Performance with 100+ task lists",
        todo_challenge4: "Inline editing without focus/blur conflicts",
        todo_solutions_title: "Solutions Provided",
        todo_solution1: "Debounce on saves + graceful fallback",
        todo_solution2: "Strict validation and input sanitization",
        todo_solution3: "Virtual scrolling and lazy rendering",
        todo_solution4: "State machine for interaction modes",
        view_code_github: "View code on GitHub",
        contact_me: "Contact me",
        // TodoList page
        todo_title: "To‑Do List Website",
        todo_eyebrow: "Task management — Pure JavaScript",
        todo_hero_title: "Elegant personal organizer",
        todo_hero_lead: "A modern website that transforms daily task management into a fluid and intuitive experience. Designed to work entirely offline with local data persistence.",
        todo_context_title: "Context & Vision",
        todo_context_p1: "This project was born from a simple observation: existing task managers are often overloaded with unnecessary features or require a permanent connection. The goal was to create a minimalist, fast, and accessible site without server dependency.",
        todo_context_p2: "By leveraging the browser's LocalStorage API, the site guarantees 100% offline availability while offering a modern interface with priority system, deadlines, and real-time search.",
        todo_implementation_title: "Technical Implementation",
        todo_features_title: "Detailed Features",
        todo_challenges_title: "Technical Challenges",
        todo_solutions_title: "Solutions Provided",
        todo_learnings_title: "Learnings & Evolutions",
        todo_learnings_p1: "This project was an opportunity to deepen DOM manipulation without a framework, master native browser APIs, and design a maintainable architecture for vanilla JavaScript. It also allowed developing strong UX sensitivity, particularly on loading state management and visual feedback.",
        todo_learnings_p2: "Future planned evolutions include: optional cloud sync, PWA with service worker, tags/categories for tasks, and JSON export/import.",
        test_site: "View site",
        discuss_project: "Discuss the project"
    },
    es: {
        nav_home: "Inicio",
        nav_about: "Acerca de",
        nav_skills: "Habilidades",
        nav_projects: "Proyectos",
        nav_contact: "Contacto",
        hero_greeting: "Hola, soy",
        hero_title: "Estudiante de Desarrollo Web",
        hero_description: "Tengo 18 años y transformo ideas en sitios web funcionales y creativos.",
        hero_btn_projects: "Ver mis proyectos",
        hero_btn_contact: "Contactarme",
        about_title: "Acerca de mí",
        about_p1: "Apasionado por la tecnología digital desde pequeño, decidí convertir esta pasión en carrera. Actualmente estudiando desarrollo web, aprendo nuevas tecnologías cada día y desarrollo mis habilidades a través de proyectos concretos.",
        about_p2: "Mi enfoque del desarrollo se basa en tres pilares: calidad de código, experiencia del usuario y aprendizaje continuo. Soy curioso, perseverante y me encanta resolver problemas complejos a través del código.",
        about_p3: "Siempre atento a las últimas tendencias web, me esfuerzo por crear sitios modernos, eficientes y accesibles.",
        stat_years: "Años",
        stat_projects: "Proyectos",
        stat_technologies: "Tecnologías",
        stat_motivation: "Motivación",
        skills_title: "Mis Habilidades",
        projects_title: "Mis Proyectos",
        project1_title: "Proyecto Docker Laravel",
        project1_description: "Dos sitios Laravel comparten una MySQL vía Docker (Nginx, PHP‑FPM); contenedores escalables.",
        project2_title: "Sitio To-Do List",
        project2_description: "Gestor de tareas: crear, filtrar, buscar; LocalStorage persistente; UI moderna y responsive.",
        project3_title: "Portafolio V1",
        project3_description: "Portafolio responsive con navegación fluida y animaciones CSS.",
        project_link: "Ver código",
        contact_title: "Contáctame",
        contact_subtitle: "¿Una oportunidad o una pregunta? ¡No dudes en escribir!",
        contact_name: "Tu Nombre",
        contact_email: "Tu Correo",
        contact_message: "Tu Mensaje",
        contact_btn: "Enviar",
        footer_rights: "Todos los derechos reservados.",
        back_to_projects: "Volver a proyectos",
        docker_title: "Proyecto Docker Laravel",
        docker_subtitle: "Arquitectura multi-aplicación con base de datos compartida vía contenedorización Docker",
        docker_about_title: "Acerca del proyecto",
        docker_about_p1: "Este proyecto representa una solución de arquitectura moderna que permite conectar dos aplicaciones web distintas a una única base de datos MySQL a través de Docker. El objetivo principal era crear un entorno de desarrollo reproducible y aislado mientras se permite el intercambio de datos entre múltiples aplicaciones Laravel.",
        docker_about_p2: "La contenedorización Docker garantiza que cada servicio funcione en su propio entorno aislado, simplificando el despliegue y reduciendo conflictos de dependencias. Este enfoque demuestra una comprensión profunda de los conceptos DevOps y arquitecturas cloud-native.",
        docker_objectives_title: "Objetivos",
        docker_features_title: "Características clave",
        docker_architecture_title: "Arquitectura técnica",
        docker_tech_title: "Tecnologías utilizadas",
        docker_skills_title: "Habilidades desarrolladas",
        docker_skill1: "Dominio de Docker y la containerización",
        docker_skill2: "Configuración y orquestación de servicios con Docker Compose",
        docker_skill3: "Gestión de redes Docker y comunicación entre contenedores",
        docker_skill4: "Administración de bases de datos MySQL",
        docker_skill5: "Configuración de servidores web Nginx",
        docker_skill6: "Comprensión de arquitecturas de microservicios",
        docker_skill7: "Gestión de volúmenes y persistencia de datos",
        docker_skill8: "Depuración y resolución de problemas en entornos containerizados",
        docker_challenges_title: "Desafíos superados",
        docker_challenge1: "Configuración de compartición de base de datos entre múltiples aplicaciones",
        docker_challenge2: "Gestión de permisos y seguridad en contenedores",
        docker_challenge3: "Optimización de configuración Nginx para rendimiento",
        docker_challenge4: "Implementación de volúmenes persistentes para desarrollo",
        docker_challenge5: "Resolución de problemas de red entre contenedores",
        docker_challenge6: "Configuración de variables de entorno Laravel para Docker",
        docker_obj_1: "Crear una arquitectura escalable y fácil de desplegar",
        docker_obj_2: "Aislar servicios y dependencias en contenedores",
        docker_obj_3: "Facilitar la colaboración mediante entornos reproducibles",
        docker_obj_4: "Optimizar flujos de desarrollo y producción",
        docker_obj_5: "Asegurar la portabilidad entre diferentes sistemas operativos",
        docker_obj_6: "Implementar las mejores prácticas de DevOps",
        docker_feat1_title: "Containerización completa",
        docker_feat1_desc: "Todos los servicios funcionan en contenedores Docker aislados",
        docker_feat2_title: "Base de datos compartida",
        docker_feat2_desc: "Un único servidor MySQL para múltiples aplicaciones",
        docker_feat3_title: "Configuración optimizada",
        docker_feat3_desc: "Archivos docker-compose.yml documentados para fácil implementación",
        docker_feat4_title: "Volúmenes persistentes",
        docker_feat4_desc: "Los datos se conservan entre reinicios de contenedores",
        docker_feat5_title: "Red aislada",
        docker_feat5_desc: "Comunicación segura entre servicios Docker",
        docker_feat6_title: "Escalabilidad",
        docker_feat6_desc: "Arquitectura diseñada para agregar nuevas aplicaciones fácilmente",
        docker_arch_services: "Servicios Docker",
        docker_arch_service1: "Primer sitio web con su propio contenedor Nginx/PHP-FPM",
        docker_arch_service2: "Segundo sitio web con configuración similar pero independiente",
        docker_arch_service3: "Servidor de base de datos compartido entre las dos aplicaciones",
        docker_arch_service4: "Servidor web y reverse proxy para cada aplicación",
        docker_arch_service5: "Gestor de procesos FastCGI para PHP",
        docker_arch_config: "Configuración",
        docker_arch_config_intro: "El proyecto utiliza Docker Compose para orquestar todos los servicios. Cada servicio se define con:",
        docker_arch_config1: "Imágenes Docker oficiales o personalizadas",
        docker_arch_config2: "Volúmenes para persistencia y desarrollo",
        docker_arch_config3: "Variables de entorno para configuración",
        docker_arch_config4: "Puertos expuestos para acceso externo",
        docker_arch_config5: "Dependencias entre servicios para orden de inicio",
        docker_tech1: "Plataforma de containerización para aislamiento y portabilidad",
        docker_tech2: "Herramienta de orquestación para gestionar múltiples contenedores",
        docker_tech3: "Framework PHP moderno para aplicaciones web",
        docker_tech4: "Sistema de gestión de bases de datos relacionales",
        docker_tech5: "Servidor web de alto rendimiento y reverse proxy",
        docker_tech6: "Gestor de procesos PHP FastCGI",
        view_code_github: "Ver código en GitHub",
        contact_me: "Contáctame",
        todo_title: "Sitio To‑Do List",
        todo_eyebrow: "Gestión de tareas — JavaScript puro",
        todo_hero_title: "Organizador personal elegante",
        todo_hero_lead: "Un sitio web moderno que transforma la gestión diaria de tareas en una experiencia fluida e intuitiva. Diseñado para funcionar completamente offline con persistencia de datos local.",
        todo_context_title: "Contexto y Visión",
        todo_context_p1: "Este proyecto nació de una simple observación: los gestores de tareas existentes suelen estar sobrecargados de funciones innecesarias o requieren una conexión permanente. El objetivo era crear un sitio minimalista, rápido y accesible sin dependencia del servidor.",
        todo_context_p2: "Aprovechando la API LocalStorage del navegador, el sitio garantiza una disponibilidad 100% offline mientras ofrece una interfaz moderna con sistema de prioridades, fechas límite y búsqueda en tiempo real.",
        todo_implementation_title: "Implementación técnica",
        todo_impl_arch: "Arquitectura modular",
        todo_impl_arch1: "objeto central sincronizando UI y storage",
        todo_impl_arch2: "generación DOM optimizada por plantillas",
        todo_impl_arch3: "gestión eficiente de interacciones",
        todo_impl_arch4: "guardado en cada modificación",
        todo_impl_tech: "Tecnologías clave",
        todo_impl_tech1_desc: "HTML5 semántico, CSS3 Grid/Flexbox",
        todo_impl_tech2_desc: "JavaScript ES6+ (clases, módulos)",
        todo_impl_tech3_desc: "LocalStorage con serialización JSON",
        todo_impl_tech4_desc: "Transiciones CSS, estados hover/focus",
        todo_feat1_title: "Creación instantánea",
        todo_feat1_desc: "Agregar tareas con título, detalles, prioridad y fecha límite en un clic.",
        todo_feat2_title: "Filtros avanzados",
        todo_feat2_desc: "Vista por estado, prioridad o fecha. Búsqueda dinámica multi-criterios.",
        todo_feat3_title: "Edición en línea",
        todo_feat3_desc: "Modificación directa sin popup, validación automática.",
        todo_feat4_title: "Diseño adaptativo",
        todo_feat4_desc: "Interfaz optimizada móvil/escritorio con tema oscuro elegante.",
        todo_feat5_title: "Gestión selectiva",
        todo_feat5_desc: "Eliminación única o en masa con confirmación visual.",
        todo_feat6_title: "100% Offline",
        todo_feat6_desc: "Sin conexión requerida, datos almacenados localmente.",
        todo_features_title: "Características detalladas",
        todo_feature1_title: "Sistema de prioridades",
        todo_feature1_desc: "Tres niveles (Ninguna, Media, Alta) con indicadores visuales y ordenamiento automático.",
        todo_feature2_title: "Fechas de vencimiento",
        todo_feature2_desc: "Selector nativo HTML5, formato localizado y alertas visuales para plazos.",
        todo_feature3_title: "Búsqueda inteligente",
        todo_feature3_desc: "Filtrado en tiempo real sobre título y detalles, insensible a mayúsculas.",
        todo_feature4_title: "Contadores dinámicos",
        todo_feature4_desc: "Estadísticas en tiempo real: tareas en curso vs terminadas.",
        todo_challenges_title: "Desafíos técnicos",
        todo_challenge1: "Sincronización estado/localStorage sin latencia perceptible",
        todo_challenge2: "Gestión de casos extremos (cuota storage, corrupción JSON)",
        todo_challenge3: "Rendimiento con listas de 100+ tareas",
        todo_challenge4: "Edición inline sin conflicto focus/blur",
        todo_solutions_title: "Soluciones proporcionadas",
        todo_solution1: "Debounce en guardados + fallback gracioso",
        todo_solution2: "Validación estricta y sanitización de entradas",
        todo_solution3: "Virtual scrolling y lazy rendering",
        todo_solution4: "Máquina de estados para modos de interacción",
        todo_learnings_title: "Aprendizajes y Evoluciones",
        todo_learnings_p1: "Este proyecto fue una oportunidad para profundizar en la manipulación del DOM sin framework, dominar las API nativas del navegador y diseñar una arquitectura mantenible para JavaScript vanilla. También permitió desarrollar una fuerte sensibilidad UX, particularmente en la gestión de estados de carga y feedback visual.",
        todo_learnings_p2: "Las evoluciones futuras planificadas incluyen: sincronización en la nube opcional, PWA con service worker, etiquetas/categorías para tareas y exportación/importación en formato JSON.",
        test_site: "Ver sitio",
        discuss_project: "Discutir el proyecto"
    },
    it: {
        nav_home: "Home",
        nav_about: "Chi sono",
        nav_skills: "Competenze",
        nav_projects: "Progetti",
        nav_contact: "Contatti",
        hero_greeting: "Ciao, sono",
        hero_title: "Studente di Sviluppo Web",
        hero_description: "Ho 18 anni e trasformo idee in siti web funzionali e creativi.",
        hero_btn_projects: "Visualizza i miei progetti",
        hero_btn_contact: "Contattami",
        about_title: "Chi sono",
        about_p1: "Appassionato di tecnologia digitale fin da piccolo, ho deciso di trasformare questa passione in carriera. Attualmente studente di sviluppo web, imparo nuove tecnologie ogni giorno e sviluppo le mie competenze attraverso progetti concreti.",
        about_p2: "Il mio approccio allo sviluppo si basa su tre pilastri: qualità del codice, esperienza dell'utente e apprendimento continuo. Sono curioso, perseverante e mi piace risolvere problemi complessi attraverso il codice.",
        about_p3: "Sempre attento alle ultime tendenze web, mi impegno a creare siti moderni, performanti e accessibili.",
        stat_years: "Anni",
        stat_projects: "Progetti",
        stat_technologies: "Tecnologie",
        stat_motivation: "Motivazione",
        skills_title: "Le mie Competenze",
        projects_title: "I miei Progetti",
        project1_title: "Progetto Docker Laravel",
        project1_description: "Due siti Laravel condividono una MySQL via Docker (Nginx, PHP‑FPM); container scalabili.",
        project2_title: "Sito To-Do List",
        project2_description: "Todo: creare, filtrare, cercare; LocalStorage; interfaccia moderna e responsive.",
        project3_title: "Portfolio V1",
        project3_description: "Portfolio responsive con navigazione fluida e animazioni CSS.",
        project_link: "Visualizza codice",
        contact_title: "Contattami",
        contact_subtitle: "Un'opportunità o una domanda? Non esitare!",
        contact_name: "Il tuo Nome",
        contact_email: "La tua Email",
        contact_message: "Il tuo Messaggio",
        contact_btn: "Invia",
        footer_rights: "Tutti i diritti riservati.",
        back_to_projects: "Torna ai progetti",
        docker_title: "Progetto Docker Laravel",
        docker_subtitle: "Architettura multi-applicazione con database condiviso tramite containerizzazione Docker",
        docker_about_title: "Sul progetto",
        docker_about_p1: "Questo progetto rappresenta una soluzione architettonica moderna che consente di connettere due applicazioni web distinte a un unico database MySQL tramite Docker. L'obiettivo principale era creare un ambiente di sviluppo riproducibile e isolato permettendo la condivisione dei dati tra più applicazioni Laravel.",
        docker_about_p2: "La containerizzazione Docker garantisce che ogni servizio funzioni nel proprio ambiente isolato, semplificando il deployment e riducendo i conflitti di dipendenze. Questo approccio dimostra una profonda comprensione dei concetti DevOps e delle architetture cloud-native.",
        docker_objectives_title: "Obiettivi",
        docker_features_title: "Caratteristiche chiave",
        docker_architecture_title: "Architettura tecnica",
        docker_tech_title: "Tecnologie utilizzate",
        docker_skills_title: "Competenze sviluppate",
        docker_skill1: "Padronanza di Docker e della containerizzazione",
        docker_skill2: "Configurazione e orchestrazione di servizi con Docker Compose",
        docker_skill3: "Gestione di reti Docker e comunicazione tra container",
        docker_skill4: "Amministrazione di database MySQL",
        docker_skill5: "Configurazione di server web Nginx",
        docker_skill6: "Comprensione di architetture a microservizi",
        docker_skill7: "Gestione di volumi e persistenza dei dati",
        docker_skill8: "Debug e risoluzione problemi in ambienti containerizzati",
        docker_challenges_title: "Sfide superate",
        docker_challenge1: "Configurazione della condivisione del database tra più applicazioni",
        docker_challenge2: "Gestione dei permessi e della sicurezza nei container",
        docker_challenge3: "Ottimizzazione della configurazione Nginx per le prestazioni",
        docker_challenge4: "Implementazione di volumi persistenti per lo sviluppo",
        docker_challenge5: "Risoluzione problemi di rete tra container",
        docker_challenge6: "Configurazione delle variabili d'ambiente Laravel per Docker",
        docker_obj_1: "Creare un'architettura scalabile e facile da implementare",
        docker_obj_2: "Isolare servizi e dipendenze in container",
        docker_obj_3: "Facilitare la collaborazione mediante ambienti riproducibili",
        docker_obj_4: "Ottimizzare i flussi di sviluppo e produzione",
        docker_obj_5: "Garantire la portabilità tra diversi sistemi operativi",
        docker_obj_6: "Implementare le migliori pratiche DevOps",
        docker_feat1_title: "Containerizzazione completa",
        docker_feat1_desc: "Tutti i servizi funzionano in container Docker isolati",
        docker_feat2_title: "Database condiviso",
        docker_feat2_desc: "Un unico server MySQL per più applicazioni",
        docker_feat3_title: "Configurazione ottimizzata",
        docker_feat3_desc: "File docker-compose.yml documentati per facile implementazione",
        docker_feat4_title: "Volumi persistenti",
        docker_feat4_desc: "I dati vengono conservati tra riavvii dei container",
        docker_feat5_title: "Rete isolata",
        docker_feat5_desc: "Comunicazione sicura tra servizi Docker",
        docker_feat6_title: "Scalabilità",
        docker_feat6_desc: "Architettura progettata per aggiungere nuove applicazioni facilmente",
        docker_arch_services: "Servizi Docker",
        docker_arch_service1: "Primo sito web con proprio container Nginx/PHP-FPM",
        docker_arch_service2: "Secondo sito web con configurazione simile ma indipendente",
        docker_arch_service3: "Server database condiviso tra le due applicazioni",
        docker_arch_service4: "Server web e reverse proxy per ogni applicazione",
        docker_arch_service5: "Gestore processi FastCGI per PHP",
        docker_arch_config: "Configurazione",
        docker_arch_config_intro: "Il progetto utilizza Docker Compose per orchestrare tutti i servizi. Ogni servizio è definito con:",
        docker_arch_config1: "Immagini Docker ufficiali o personalizzate",
        docker_arch_config2: "Volumi per persistenza e sviluppo",
        docker_arch_config3: "Variabili d'ambiente per configurazione",
        docker_arch_config4: "Porte esposte per accesso esterno",
        docker_arch_config5: "Dipendenze tra servizi per ordine di avvio",
        docker_tech1: "Piattaforma di containerizzazione per isolamento e portabilità",
        docker_tech2: "Strumento di orchestrazione per gestire più container",
        docker_tech3: "Framework PHP moderno per applicazioni web",
        docker_tech4: "Sistema di gestione database relazionale",
        docker_tech5: "Server web ad alte prestazioni e reverse proxy",
        docker_tech6: "Gestore processi PHP FastCGI",
        view_code_github: "Visualizza codice su GitHub",
        contact_me: "Contattami",
        todo_title: "Sito To‑Do List",
        todo_eyebrow: "Gestione attività — JavaScript puro",
        todo_hero_title: "Organizzatore personale elegante",
        todo_hero_lead: "Un sito web moderno che trasforma la gestione quotidiana delle attività in un'esperienza fluida e intuitiva. Progettato per funzionare completamente offline con persistenza dei dati locale.",
        todo_context_title: "Contesto e Visione",
        todo_context_p1: "Questo progetto è nato da una semplice osservazione: i gestori di attività esistenti sono spesso sovraccarichi di funzionalità inutili o richiedono una connessione permanente. L'obiettivo era creare un sito minimalista, veloce e accessibile senza dipendenza dal server.",
        todo_context_p2: "Sfruttando l'API LocalStorage del browser, il sito garantisce una disponibilità 100% offline offrendo un'interfaccia moderna con sistema di priorità, scadenze e ricerca in tempo reale.",
        todo_implementation_title: "Implementazione tecnica",
        todo_impl_arch: "Architettura modulare",
        todo_impl_arch1: "oggetto centrale per sincronizzare UI e storage",
        todo_impl_arch2: "generazione DOM ottimizzata tramite template",
        todo_impl_arch3: "gestione performante delle interazioni",
        todo_impl_arch4: "salvataggio ad ogni modifica",
        todo_impl_tech: "Tecnologie chiave",
        todo_impl_tech1_desc: "HTML5 semantico, CSS3 Grid/Flexbox",
        todo_impl_tech2_desc: "JavaScript ES6+ (classi, moduli)",
        todo_impl_tech3_desc: "LocalStorage con serializzazione JSON",
        todo_impl_tech4_desc: "Transizioni CSS, stati hover/focus",
        todo_feat1_title: "Creazione istantanea",
        todo_feat1_desc: "Aggiungere attività con titolo, dettagli, priorità e scadenza in un clic.",
        todo_feat2_title: "Filtri avanzati",
        todo_feat2_desc: "Vista per stato, priorità o data. Ricerca dinamica multi-criteri.",
        todo_feat3_title: "Modifica in linea",
        todo_feat3_desc: "Modifica diretta senza popup, convalida automatica.",
        todo_feat4_title: "Design adattivo",
        todo_feat4_desc: "Interfaccia ottimizzata mobile/desktop con tema scuro elegante.",
        todo_feat5_title: "Gestione selettiva",
        todo_feat5_desc: "Eliminazione singola o di massa con conferma visiva.",
        todo_feat6_title: "100% Offline",
        todo_feat6_desc: "Nessuna connessione richiesta, dati memorizzati localmente.",
        todo_features_title: "Caratteristiche dettagliate",
        todo_feature1_title: "Sistema di priorità",
        todo_feature1_desc: "Tre livelli (Nessuna, Media, Alta) con indicatori visivi e ordinamento automatico.",
        todo_feature2_title: "Date di scadenza",
        todo_feature2_desc: "Selettore nativo HTML5, formato localizzato e avvisi visivi per le scadenze.",
        todo_feature3_title: "Ricerca intelligente",
        todo_feature3_desc: "Filtraggio in tempo reale su titolo e dettagli, insensibile alle maiuscole.",
        todo_feature4_title: "Contatori dinamici",
        todo_feature4_desc: "Statistiche in tempo reale: attività in corso vs completate.",
        todo_challenges_title: "Sfide tecniche",
        todo_challenge1: "Sincronizzazione stato/localStorage senza latenza percettibile",
        todo_challenge2: "Gestione di casi limite (quota storage, corruzione JSON)",
        todo_challenge3: "Prestazioni con elenchi di oltre 100 attività",
        todo_challenge4: "Modifica inline senza conflitto focus/blur",
        todo_solutions_title: "Soluzioni fornite",
        todo_solution1: "Debounce sui salvataggi + fallback gracioso",
        todo_solution2: "Validazione rigorosa e sanitizzazione degli input",
        todo_solution3: "Virtual scrolling e lazy rendering",
        todo_solution4: "Macchina a stati per modalità di interazione",
        todo_learnings_title: "Apprendimenti ed Evoluzioni",
        todo_learnings_p1: "Questo progetto è stato un'opportunità per approfondire la manipolazione del DOM senza framework, padroneggiare le API native del browser e progettare un'architettura manutenibile per JavaScript vanilla. Ha anche permesso di sviluppare una forte sensibilità UX, in particolare sulla gestione degli stati di caricamento e feedback visivi.",
        todo_learnings_p2: "Le evoluzioni future previste includono: sincronizzazione cloud opzionale, PWA con service worker, tag/categorie per le attività e esportazione/importazione in formato JSON.",
        test_site: "Visualizza sito",
        discuss_project: "Discuti del progetto"
    },
    de: {
        nav_home: "Startseite",
        nav_about: "Über mich",
        nav_skills: "Fähigkeiten",
        nav_projects: "Projekte",
        nav_contact: "Kontakt",
        hero_greeting: "Hallo, ich bin",
        hero_title: "Webentwicklungs-Student",
        hero_description: "Ich bin 18 Jahre alt und verwandle Ideen in funktionale und kreative Websites.",
        hero_btn_projects: "Meine Projekte anschauen",
        hero_btn_contact: "Kontaktieren Sie mich",
        about_title: "Über mich",
        about_p1: "Leidenschaftlich für digitale Technologie seit meiner Kindheit, habe ich mich entschieden, diese Leidenschaft in eine Karriere umzuwandeln. Derzeit studiere ich Webentwicklung, lerne jeden Tag neue Technologien und entwickle meine Fähigkeiten durch konkrete Projekte.",
        about_p2: "Mein Entwicklungsansatz basiert auf drei Säulen: Codequalität, Benutzererfahrung und kontinuierliches Lernen. Ich bin neugierig, ausdauernd und liebe es, komplexe Probleme durch Code zu lösen.",
        about_p3: "Immer auf die neuesten Web-Trends aufmerksam, bemühe ich mich, moderne, leistungsstarke und barrierefreie Websites zu erstellen.",
        stat_years: "Jahre",
        stat_projects: "Projekte",
        stat_technologies: "Technologien",
        stat_motivation: "Motivation",
        skills_title: "Meine Fähigkeiten",
        projects_title: "Meine Projekte",
        project1_title: "Docker Laravel Projekt",
        project1_description: "Zwei Laravel-Websites teilen MySQL via Docker (Nginx, PHP‑FPM); containerisiert und skalierbar.",
        project2_title: "To-Do-Listen-Website",
        project2_description: "Aufgabenmanager: erstellen, filtern, suchen; LocalStorage; moderne responsive UI.",
        project3_title: "Portfolio V1",
        project3_description: "Responsives Portfolio mit flüssiger Navigation und CSS-Animationen.",
        project_link: "Code anschauen",
        contact_title: "Kontaktieren Sie mich",
        contact_subtitle: "Eine Gelegenheit oder eine Frage? Zögern Sie nicht!",
        contact_name: "Ihr Name",
        contact_email: "Ihre E-Mail",
        contact_message: "Ihre Nachricht",
        contact_btn: "Senden",
        footer_rights: "Alle Rechte vorbehalten.",
        back_to_projects: "Zurück zu Projekten",
        docker_title: "Docker Laravel Projekt",
        docker_subtitle: "Multi-Anwendungsarchitektur mit gemeinsamer Datenbank via Docker-Containerisierung",
        docker_about_title: "Über das Projekt",
        docker_about_p1: "Dieses Projekt stellt eine moderne Architekturlösung dar, die es ermöglicht, zwei verschiedene Webanwendungen über Docker mit einer einzigen MySQL-Datenbank zu verbinden. Das Hauptziel war es, eine reproduzierbare und isolierte Entwicklungsumgebung zu schaffen und gleichzeitig den Datenaustausch zwischen mehreren Laravel-Anwendungen zu ermöglichen.",
        docker_about_p2: "Die Docker-Containerisierung stellt sicher, dass jeder Dienst in seiner eigenen isolierten Umgebung läuft, was die Bereitstellung vereinfacht und Abhängigkeitskonflikte reduziert. Dieser Ansatz demonstriert ein tiefes Verständnis von DevOps-Konzepten und Cloud-nativen Architekturen.",
        docker_objectives_title: "Ziele",
        docker_features_title: "Hauptmerkmale",
        docker_architecture_title: "Technische Architektur",
        docker_tech_title: "Verwendete Technologien",
        docker_skills_title: "Entwickelte Fähigkeiten",
        docker_skill1: "Beherrschung von Docker und Containerisierung",
        docker_skill2: "Konfiguration und Orchestrierung von Diensten mit Docker Compose",
        docker_skill3: "Verwaltung von Docker-Netzwerken und Container-Kommunikation",
        docker_skill4: "MySQL-Datenbankverwaltung",
        docker_skill5: "Nginx-Webserver-Konfiguration",
        docker_skill6: "Verständnis von Microservice-Architekturen",
        docker_skill7: "Verwaltung von Volumes und Datenpersistenz",
        docker_skill8: "Debugging und Problemlösung in containerisierten Umgebungen",
        docker_challenges_title: "Gemeisterte Herausforderungen",
        docker_challenge1: "Konfiguration der Datenbankfreigabe zwischen mehreren Anwendungen",
        docker_challenge2: "Verwaltung von Berechtigungen und Sicherheit in Containern",
        docker_challenge3: "Optimierung der Nginx-Konfiguration für Leistung",
        docker_challenge4: "Implementierung persistenter Volumes für die Entwicklung",
        docker_challenge5: "Lösung von Netzwerkproblemen zwischen Containern",
        docker_challenge6: "Konfiguration von Laravel-Umgebungsvariablen für Docker",
        docker_obj_1: "Eine skalierbare und leicht bereitzustellende Architektur schaffen",
        docker_obj_2: "Dienste und Abhängigkeiten in Containern isolieren",
        docker_obj_3: "Zusammenarbeit durch reproduzierbare Umgebungen erleichtern",
        docker_obj_4: "Entwicklungs- und Produktionsabläufe optimieren",
        docker_obj_5: "Portabilität zwischen verschiedenen Betriebssystemen sicherstellen",
        docker_obj_6: "DevOps-Best-Practices implementieren",
        docker_feat1_title: "Vollständige Containerisierung",
        docker_feat1_desc: "Alle Dienste laufen in isolierten Docker-Containern",
        docker_feat2_title: "Gemeinsame Datenbank",
        docker_feat2_desc: "Ein einziger MySQL-Server für mehrere Anwendungen",
        docker_feat3_title: "Optimierte Konfiguration",
        docker_feat3_desc: "Dokumentierte docker-compose.yml-Dateien für einfache Bereitstellung",
        docker_feat4_title: "Persistente Volumes",
        docker_feat4_desc: "Daten bleiben zwischen Container-Neustarts erhalten",
        docker_feat5_title: "Isoliertes Netzwerk",
        docker_feat5_desc: "Sichere Kommunikation zwischen Docker-Diensten",
        docker_feat6_title: "Skalierbarkeit",
        docker_feat6_desc: "Architektur zum einfachen Hinzufügen neuer Anwendungen ausgelegt",
        docker_arch_services: "Docker-Dienste",
        docker_arch_service1: "Erste Website mit eigenem Nginx/PHP-FPM-Container",
        docker_arch_service2: "Zweite Website mit ähnlicher aber unabhängiger Konfiguration",
        docker_arch_service3: "Gemeinsamer Datenbankserver für beide Anwendungen",
        docker_arch_service4: "Webserver und Reverse-Proxy für jede Anwendung",
        docker_arch_service5: "FastCGI-Prozessmanager für PHP",
        docker_arch_config: "Konfiguration",
        docker_arch_config_intro: "Das Projekt verwendet Docker Compose zur Orchestrierung aller Dienste. Jeder Dienst wird definiert mit:",
        docker_arch_config1: "Offizielle oder angepasste Docker-Images",
        docker_arch_config2: "Volumes für Persistenz und Entwicklung",
        docker_arch_config3: "Umgebungsvariablen für Konfiguration",
        docker_arch_config4: "Freigegebene Ports für externen Zugriff",
        docker_arch_config5: "Abhängigkeiten zwischen Diensten für Startreihenfolge",
        docker_tech1: "Containerisierungsplattform für Isolation und Portabilität",
        docker_tech2: "Orchestrierungs-Tool zur Verwaltung mehrerer Container",
        docker_tech3: "Modernes PHP-Framework für Webanwendungen",
        docker_tech4: "Relationales Datenbankverwaltungssystem",
        docker_tech5: "Hochleistungs-Webserver und Reverse-Proxy",
        docker_tech6: "PHP-FastCGI-Prozessmanager",
        view_code_github: "Code auf GitHub ansehen",
        contact_me: "Kontaktieren Sie mich",
        todo_title: "To‑Do-Listen-Website",
        todo_eyebrow: "Aufgabenverwaltung — Reines JavaScript",
        todo_hero_title: "Eleganter persönlicher Organizer",
        todo_hero_lead: "Eine moderne Website, die die tägliche Aufgabenverwaltung in eine flüssige und intuitive Erfahrung verwandelt. Entwickelt, um vollständig offline mit lokaler Datenpersistenz zu funktionieren.",
        todo_context_title: "Kontext & Vision",
        todo_context_p1: "Dieses Projekt entstand aus einer einfachen Beobachtung: Bestehende Aufgabenmanager sind oft mit unnötigen Funktionen überladen oder erfordern eine permanente Verbindung. Das Ziel war es, eine minimalistische, schnelle und zugängliche Website ohne Serverabhängigkeit zu erstellen.",
        todo_context_p2: "Durch die Nutzung der LocalStorage-API des Browsers garantiert die Website eine 100%ige Offline-Verfügbarkeit und bietet gleichzeitig eine moderne Oberfläche mit Prioritätssystem, Fristen und Echtzeit-Suche.",
        todo_implementation_title: "Technische Implementierung",
        todo_impl_arch: "Modulare Architektur",
        todo_impl_arch1: "zentrales Objekt zur Synchronisation von UI und Storage",
        todo_impl_arch2: "optimierte DOM-Generierung durch Templates",
        todo_impl_arch3: "performante Verwaltung von Interaktionen",
        todo_impl_arch4: "Speicherung bei jeder Änderung",
        todo_impl_tech: "Schlüsseltechnologien",
        todo_impl_tech1_desc: "Semantisches HTML5, CSS3 Grid/Flexbox",
        todo_impl_tech2_desc: "JavaScript ES6+ (Klassen, Module)",
        todo_impl_tech3_desc: "LocalStorage mit JSON-Serialisierung",
        todo_impl_tech4_desc: "CSS-Übergänge, Hover/Focus-Zustände",
        todo_feat1_title: "Sofortige Erstellung",
        todo_feat1_desc: "Aufgaben mit Titel, Details, Priorität und Frist mit einem Klick hinzufügen.",
        todo_feat2_title: "Erweiterte Filter",
        todo_feat2_desc: "Ansicht nach Status, Priorität oder Datum. Dynamische Multi-Kriterien-Suche.",
        todo_feat3_title: "Inline-Bearbeitung",
        todo_feat3_desc: "Direkte Änderung ohne Popup, automatische Validierung.",
        todo_feat4_title: "Adaptives Design",
        todo_feat4_desc: "Mobile/Desktop-optimierte Oberfläche mit elegantem dunklem Thema.",
        todo_feat5_title: "Selektive Verwaltung",
        todo_feat5_desc: "Einzelne oder Massenlöschung mit visueller Bestätigung.",
        todo_feat6_title: "100% Offline",
        todo_feat6_desc: "Keine Verbindung erforderlich, Daten lokal gespeichert.",
        todo_features_title: "Detaillierte Funktionen",
        todo_feature1_title: "Prioritätssystem",
        todo_feature1_desc: "Drei Stufen (Keine, Mittel, Hoch) mit visuellen Indikatoren und automatischer Sortierung.",
        todo_feature2_title: "Fristen",
        todo_feature2_desc: "Nativer HTML5-Selektor, lokalisiertes Format und visuelle Warnungen für Deadlines.",
        todo_feature3_title: "Intelligente Suche",
        todo_feature3_desc: "Echtzeit-Filterung nach Titel und Details, Groß-/Kleinschreibung wird ignoriert.",
        todo_feature4_title: "Dynamische Zähler",
        todo_feature4_desc: "Echtzeit-Statistiken: laufende vs. abgeschlossene Aufgaben.",
        todo_challenges_title: "Technische Herausforderungen",
        todo_challenge1: "Synchronisation von Zustand/LocalStorage ohne wahrnehmbare Latenz",
        todo_challenge2: "Verwaltung von Randfällen (Storage-Kontingent, JSON-Korruption)",
        todo_challenge3: "Leistung mit Listen von über 100 Aufgaben",
        todo_challenge4: "Inline-Bearbeitung ohne Focus/Blur-Konflikt",
        todo_solutions_title: "Bereitgestellte Lösungen",
        todo_solution1: "Debounce bei Speicherungen + graceful Fallback",
        todo_solution2: "Strikte Validierung und Bereinigung von Eingaben",
        todo_solution3: "Virtual Scrolling und Lazy Rendering",
        todo_solution4: "Zustandsmaschine für Interaktionsmodi",
        todo_learnings_title: "Erkenntnisse & Entwicklungen",
        todo_learnings_p1: "Dieses Projekt bot die Möglichkeit, die DOM-Manipulation ohne Framework zu vertiefen, native Browser-APIs zu beherrschen und eine wartbare Architektur für Vanilla-JavaScript zu entwerfen. Es ermöglichte auch die Entwicklung einer starken UX-Sensibilität, insbesondere bei der Verwaltung von Ladezuständen und visuellem Feedback.",
        todo_learnings_p2: "Geplante zukünftige Entwicklungen umfassen: optionale Cloud-Synchronisierung, PWA mit Service Worker, Tags/Kategorien für Aufgaben und JSON-Export/Import.",
        test_site: "Website ansehen",
        discuss_project: "Projekt besprechen"
    },
    ja: {
        nav_home: "ホーム",
        nav_about: "自己紹介",
        nav_skills: "スキル",
        nav_projects: "プロジェクト",
        nav_contact: "お問い合わせ",
        hero_greeting: "こんにちは、私は",
        hero_title: "ウェブ開発学生",
        hero_description: "私は18歳で、アイデアを機能的で創造的なウェブサイトに変えています。",
        hero_btn_projects: "私のプロジェクトを見る",
        hero_btn_contact: "お問い合わせ",
        about_title: "自己紹介",
        about_p1: "幼い頃からデジタル技術に情熱を持ち、この情熱をキャリアに変えることに決めました。現在ウェブ開発を学んでおり、毎日新しい技術を学び、具体的なプロジェクトを通じてスキルを開発しています。",
        about_p2: "私の開発アプローチは3つの柱に基づいています：コード品質、ユーザー体験、継続的な学習。私は好奇心旺盛で、粘り強く、コードを通じて複雑な問題を解決するのが好きです。",
        about_p3: "常にウェブの最新トレンドに注意を払い、モダンで高性能でアクセシブルなウェブサイトを作成することに努めています。",
        stat_years: "年",
        stat_projects: "プロジェクト",
        stat_technologies: "技術",
        stat_motivation: "モチベーション",
        skills_title: "私のスキル",
        projects_title: "私のプロジェクト",
        project1_title: "Docker Laravelプロジェクト",
        project1_description: "2つのLaravelサイトがDockerで1つのMySQLを共有（Nginx・PHP‑FPM）；コンテナ化でスケール。",
        project2_title: "To-Doリストサイト",
        project2_description: "タスク管理：作成・フィルター・検索。LocalStorage保存、モダンでレスポンシブ。",
        project3_title: "ポートフォリオV1",
        project3_description: "レスポンシブなポートフォリオ。滑らかなナビとCSSアニメーション。",
        project_link: "コードを見る",
        contact_title: "お問い合わせ",
        contact_subtitle: "チャンスか質問がありますか？ためらわずにお知らせください！",
        contact_name: "お名前",
        contact_email: "メールアドレス",
        contact_message: "メッセージ",
        contact_btn: "送信",
        footer_rights: "著作権所有。",
        back_to_projects: "プロジェクトに戻る",
        docker_title: "Docker Laravelプロジェクト",
        docker_subtitle: "Dockerコンテナ化による共有データベースを持つマルチアプリケーションアーキテクチャ",
        docker_about_title: "プロジェクトについて",
        docker_about_p1: "このプロジェクトは、Dockerを介して2つの異なるWebアプリケーションを単一のMySQLデータベースに接続できる最新のアーキテクチャソリューションを表しています。主な目的は、複数のLaravelアプリケーション間でのデータ共有を可能にしながら、再現可能で分離された開発環境を作成することでした。",
        docker_about_p2: "Dockerコンテナ化により、各サービスが独自の分離された環境で動作することが保証され、デプロイが簡素化され、依存関係の競合が減少します。このアプローチは、DevOpsコンセプトとクラウドネイティブアーキテクチャの深い理解を示しています。",
        docker_objectives_title: "目標",
        docker_features_title: "主な機能",
        docker_architecture_title: "技術アーキテクチャ",
        docker_tech_title: "使用技術",
        docker_skills_title: "開発されたスキル",
        docker_skill1: "Dockerとコンテナ化の習得",
        docker_skill2: "Docker Composeによるサービスの構成とオーケストレーション",
        docker_skill3: "Dockerネットワークとコンテナ間通信の管理",
        docker_skill4: "MySQLデータベース管理",
        docker_skill5: "Nginx Webサーバー構成",
        docker_skill6: "マイクロサービスアーキテクチャの理解",
        docker_skill7: "ボリュームとデータ永続化の管理",
        docker_skill8: "コンテナ化環境でのデバッグと問題解決",
        docker_challenges_title: "克服した課題",
        docker_challenge1: "複数のアプリケーション間でのデータベース共有の構成",
        docker_challenge2: "コンテナ内の権限とセキュリティの管理",
        docker_challenge3: "パフォーマンスのためのNginx構成の最適化",
        docker_challenge4: "開発用の永続ボリュームの実装",
        docker_challenge5: "コンテナ間のネットワーク問題の解決",
        docker_challenge6: "Docker用のLaravel環境変数の構成",
        docker_obj_1: "スケーラブルでデプロイしやすいアーキテクチャを作成",
        docker_obj_2: "サービスと依存関係をコンテナに分離",
        docker_obj_3: "再現可能な環境による協働を促進",
        docker_obj_4: "開発と本番のワークフローを最適化",
        docker_obj_5: "異なるオペレーティングシステム間での移植性を確保",
        docker_obj_6: "DevOpsベストプラクティスを実装",
        docker_feat1_title: "完全なコンテナ化",
        docker_feat1_desc: "すべてのサービスが分離されたDockerコンテナで実行",
        docker_feat2_title: "共有データベース",
        docker_feat2_desc: "複数のアプリケーション用の単一のMySQLサーバー",
        docker_feat3_title: "最適化された構成",
        docker_feat3_desc: "簡単にデプロイできるよう文書化されたdocker-compose.ymlファイル",
        docker_feat4_title: "永続ボリューム",
        docker_feat4_desc: "コンテナの再起動間でデータが保持される",
        docker_feat5_title: "分離されたネットワーク",
        docker_feat5_desc: "Dockerサービス間の安全な通信",
        docker_feat6_title: "スケーラビリティ",
        docker_feat6_desc: "新しいアプリケーションを簡単に追加できるように設計されたアーキテクチャ",
        docker_arch_services: "Dockerサービス",
        docker_arch_service1: "独自のNginx/PHP-FPMコンテナを持つ最初のWebサイト",
        docker_arch_service2: "類似しているが独立した構成を持つ2番目のWebサイト",
        docker_arch_service3: "2つのアプリケーション間で共有されるデータベースサーバー",
        docker_arch_service4: "各アプリケーション用のWebサーバーとリバースプロキシ",
        docker_arch_service5: "PHP用のFastCGIプロセスマネージャー",
        docker_arch_config: "構成",
        docker_arch_config_intro: "プロジェクトは、すべてのサービスをオーケストレーションするためにDocker Composeを使用します。各サービスは次のように定義されています：",
        docker_arch_config1: "公式またはカスタムのDockerイメージ",
        docker_arch_config2: "永続化と開発のためのボリューム",
        docker_arch_config3: "構成のための環境変数",
        docker_arch_config4: "外部アクセスのための公開ポート",
        docker_arch_config5: "起動順序のためのサービス間の依存関係",
        docker_tech1: "分離と移植性のためのコンテナ化プラットフォーム",
        docker_tech2: "複数のコンテナを管理するためのオーケストレーションツール",
        docker_tech3: "Webアプリケーション用の最新のPHPフレームワーク",
        docker_tech4: "リレーショナルデータベース管理システム",
        docker_tech5: "高性能Webサーバーとリバースプロキシ",
        docker_tech6: "PHP FastCGIプロセスマネージャー",
        view_code_github: "GitHubでコードを見る",
        contact_me: "お問い合わせ",
        todo_title: "To‑Doリストサイト",
        todo_eyebrow: "タスク管理 — 純粋なJavaScript",
        todo_hero_title: "エレガントな個人用オーガナイザー",
        todo_hero_lead: "日常のタスク管理をスムーズで直感的な体験に変える現代的なWebサイト。ローカルデータの永続化により完全にオフラインで動作するように設計されています。",
        todo_context_title: "コンテキストとビジョン",
        todo_context_p1: "このプロジェクトは、既存のタスクマネージャーが不要な機能で過負荷になっているか、常時接続を必要とするという単純な観察から生まれました。目標は、サーバー依存なしでミニマル、高速、アクセシブルなサイトを作成することでした。",
        todo_context_p2: "ブラウザのLocalStorage APIを活用することで、優先度システム、期限、リアルタイム検索を備えた最新のインターフェースを提供しながら、100%オフライン可用性を保証します。",
        todo_implementation_title: "技術実装",
        todo_impl_arch: "モジュラーアーキテクチャ",
        todo_impl_arch1: "UIとストレージを同期する中心的なオブジェクト",
        todo_impl_arch2: "テンプレートによる最適化されたDOM生成",
        todo_impl_arch3: "インタラクションの効率的な管理",
        todo_impl_arch4: "変更ごとの保存",
        todo_impl_tech: "主要技術",
        todo_impl_tech1_desc: "セマンティックHTML5、CSS3 Grid/Flexbox",
        todo_impl_tech2_desc: "JavaScript ES6+（クラス、モジュール）",
        todo_impl_tech3_desc: "JSONシリアル化によるLocalStorage",
        todo_impl_tech4_desc: "CSSトランジション、hover/focus状態",
        todo_feat1_title: "即座の作成",
        todo_feat1_desc: "ワンクリックでタイトル、詳細、優先度、期限を持つタスクを追加。",
        todo_feat2_title: "高度なフィルター",
        todo_feat2_desc: "ステータス、優先度、または日付別のビュー。動的な多基準検索。",
        todo_feat3_title: "インライン編集",
        todo_feat3_desc: "ポップアップなしの直接変更、自動検証。",
        todo_feat4_title: "適応型デザイン",
        todo_feat4_desc: "エレガントなダークテーマを備えたモバイル/デスクトップ最適化インターフェース。",
        todo_feat5_title: "選択的管理",
        todo_feat5_desc: "視覚的確認付きの単一または一括削除。",
        todo_feat6_title: "100%オフライン",
        todo_feat6_desc: "接続不要、データはローカルに保存。",
        todo_features_title: "詳細な機能",
        todo_feature1_title: "優先度システム",
        todo_feature1_desc: "視覚的インジケーターと自動ソート付きの3つのレベル（なし、中、高）。",
        todo_feature2_title: "期限",
        todo_feature2_desc: "ネイティブHTML5セレクター、ローカライズされた形式、デッドラインの視覚的アラート。",
        todo_feature3_title: "インテリジェント検索",
        todo_feature3_desc: "タイトルと詳細のリアルタイムフィルタリング、大文字小文字を区別しない。",
        todo_feature4_title: "動的カウンター",
        todo_feature4_desc: "リアルタイム統計：進行中のタスクvs完了したタスク。",
        todo_challenges_title: "技術的課題",
        todo_challenge1: "知覚できるレイテンシなしでのstate/localStorageの同期",
        todo_challenge2: "エッジケースの管理（ストレージクォータ、JSON破損）",
        todo_challenge3: "100以上のタスクのリストでのパフォーマンス",
        todo_challenge4: "focus/blurの競合なしでのインライン編集",
        todo_solutions_title: "提供されたソリューション",
        todo_solution1: "保存時のデバウンス + グレースフルフォールバック",
        todo_solution2: "厳格な検証と入力のサニタイゼーション",
        todo_solution3: "仮想スクロールとレイジーレンダリング",
        todo_solution4: "インタラクションモードのステートマシン",
        todo_learnings_title: "学習と進化",
        todo_learnings_p1: "このプロジェクトは、フレームワークなしのDOM操作を深め、ネイティブブラウザAPIをマスターし、バニラJavaScriptの保守可能なアーキテクチャを設計する機会でした。ローディング状態の管理とビジュアルフィードバックに関して、強いUX感性を開発することもできました。",
        todo_learnings_p2: "計画されている将来の進化には、オプションのクラウド同期、サービスワーカーを使用したPWA、タスクのタグ/カテゴリ、JSON形式でのエクスポート/インポートが含まれます。",
        test_site: "サイトを見る",
        discuss_project: "プロジェクトについて議論する"
    }
};

let currentLang = 'fr';

// Fonction pour changer la langue
function switchLanguage(lang) {
    if (lang && translations[lang]) {
        currentLang = lang;
    }
    
    // Mettre à jour l'icône du drapeau
    const langIcon = document.querySelector('.lang-icon');
    const langEmojis = {
        'fr': '🇫🇷',
        'en': '🇬🇧',
        'es': '🇪🇸',
        'it': '🇮🇹',
        'de': '🇩🇪',
        'ja': '🇯🇵'
    };
    langIcon.textContent = langEmojis[currentLang] || '🇫🇷';
    
    // Traduire tous les éléments avec data-translate
    document.querySelectorAll('[data-translate]').forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[currentLang][key]) {
            element.textContent = translations[currentLang][key];
        }
    });
    
    // Traduire les placeholders
    document.querySelectorAll('[data-translate-placeholder]').forEach(element => {
        const key = element.getAttribute('data-translate-placeholder');
        if (translations[currentLang][key]) {
            element.placeholder = translations[currentLang][key];
        }
    });
    
    // Mettre à jour le titre de la page
    const pageTitles = {
        'fr': 'Thomas Cornu | Développeur Web Junior',
        'en': 'Thomas Cornu | Junior Web Developer',
        'es': 'Thomas Cornu | Desarrollador Web Junior',
        'it': 'Thomas Cornu | Sviluppatore Web Junior',
        'de': 'Thomas Cornu | Junior-Webentwickler',
        'ja': 'Thomas Cornu | ジュニアウェブ開発者'
    };
    document.title = pageTitles[currentLang] || 'Thomas Cornu | Développeur Web Junior';
    
    // Sauvegarder la préférence
    localStorage.setItem('preferredLanguage', currentLang);
}

// Charger la langue préférée au démarrage
const savedLang = localStorage.getItem('preferredLanguage');
if (savedLang && savedLang !== currentLang) {
    switchLanguage(savedLang);
}

// Ordre des langues pour le cycle
const languages = ['fr', 'en', 'es', 'it', 'de', 'ja'];

// Ajouter l'événement au bouton de langue pour passer à la suivante
document.getElementById('langToggle').addEventListener('click', (e) => {
    e.stopPropagation();
    const currentIndex = languages.indexOf(currentLang);
    const nextIndex = (currentIndex + 1) % languages.length;
    const nextLang = languages[nextIndex];
    switchLanguage(nextLang);
});